name: CD

on:
  push:
    branches:
    - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script test

    - name: Generating documentation...
      uses: impresscms-dev/generate-phpdocs-with-clean-phpdoc-md-action@v0.1.4
      with:
        class_root_namespace: Nikeee\
        included_classes: Nikeee\**
        output_path: ./docs/

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: gh-pages
        folder: docs
        single-commit: true
